### ISSUE TITLE
Hide version numbers for Apache and Debian

### ISSUE THREAD

**Issue by Mihai98924** [Inter-Actief/Beheer_Issues#102]
To not get flagged anymore for showing the version numbers of apache and debian we need to hide them.

**Comment by Kurocon** [comment]
Done in 
https://gitlab.ia.utwente.nl/Beheer/salt-config/-/commit/e6e2902de13aa93935ec78c3655ce261f6b9f5b0
and 
https://gitlab.ia.utwente.nl/Beheer/salt-config/-/commit/9daed526c06b0d7625193ca54ead5d854740dbcf
and
https://gitlab.ia.utwente.nl/Beheer/salt-config/-/commit/ceace50c05bf8435e361d0bbc03d76d12780fe82
