### ISSUE TITLE
update Mediawiki

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#15]
[trac #1476](https://trac.ia.utwente.nl/beheer/ticket/1476)

According to the [Mediawiki mailinglist](​https://lists.wikimedia.org/pipermail/mediawiki-announce/2017-November/000214.html), the version of Mediawiki we run has just entered end-of-life. Let's update it sometime. (We do need to make sure all plugins are still compatible).

**Update: 2 years later, we still haven't updated**

**Comment by maarten0912** [comment]
Currently the plugins used are:
- [IA-MW-LdapGroups](https://github.com/Inter-Actief/IA-MW-LdapGroups)
- [BreadCrumbs](https://www.mediawiki.org/wiki/Extension:BreadCrumbs)
- [Lockdown](https://mediawiki.org/wiki/Extension:Lockdown)
- [MW-IA-OAuth2Client](https://github.com/Inter-Actief/IA-MW-OAuth2Client)
- [PluggableAuth](https://www.mediawiki.org/wiki/Extension:PluggableAuth)

What we can do with the plugins with the newest version as of now (1.39):
- [IA-MW-LdapGroups](https://github.com/Inter-Actief/IA-MW-LdapGroups) might be replaceable by the extension it is based on, [LDAPGroups](https://www.mediawiki.org/wiki/Extension:LDAPGroups). Maybe the extension has to be modified a bit.
-  [BreadCrumbs](https://www.mediawiki.org/wiki/Extension:BreadCrumbs) can be replaced by the similar [JSBreadCrumbs](https://www.mediawiki.org/wiki/Extension:JSBreadCrumbs), or the in my opinion more user friendly [BreadCrumbs2](https://www.mediawiki.org/wiki/Extension:BreadCrumbs2)
-  [Lockdown](https://mediawiki.org/wiki/Extension:Lockdown) should already be compatible
- [MW-IA-OAuth2Client](https://github.com/Inter-Actief/IA-MW-OAuth2Client) might be replaceable by [OAuth2 Client](https://www.mediawiki.org/wiki/Extension:OAuth2_Client) (it was not based on it). Maybe the extension has to be modified a bit.
- [PluggableAuth](https://www.mediawiki.org/wiki/Extension:PluggableAuth) should already be compatible.

**Comment by Kurocon** [comment]
We gave up on updating. https://wiki.ia.utwente.nl/ is now migrated to Wiki.JS
