### ISSUE TITLE
add a self-hosted Overleaf instance

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#17]
[trac #1468](https://trac.ia.utwente.nl/beheer/ticket/1468)

The trac issue originally talked about a self-hosted ShareLatex instance, however, as they have merged with Overleaf and Overleaf is now open source, we could look into hosting an Overleaf instance for Inter-_Actief_.

[github.com/overleaf/overleaf](https://github.com/overleaf/overleaf)

**Comment by Kurocon** [comment]
We can also look into https://github.com/sagemathinc/cocalc-docker (image available https://hub.docker.com/r/sagemathinc/cocalc )

Because I remember overleaf/sharelatex being notoriously difficult to install the last time we tried it

**Comment by jeffreybakker** [comment]
I personally tried a self-hosted overleaf instance recently and it was not too difficult to set up. However, the free self-hosted instance offers fewer features than the managed service; one of the missing features is the review functionality.
