### ISSUE TITLE
add backups of Magica to SNT

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#18]
[trac #1467](https://trac.ia.utwente.nl/beheer/ticket/1467)

> Bij magica is het nog niet geregeld dat er backups tegen snt aangegooid worden. Het is handig als we dit wel gaan doen.

When SNT does support backups again, we should fix that for magica.

**Comment by Kurocon** [comment]
Outdated, zie #66
