### ISSUE TITLE
RADIUS still being used in some places

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#27]
I received an e-mail from the LISA person that helped us with the RADIUS migration that we are still apparently using RADIUS in some way.

Apparently the connections are all from ia-www3.ia.utwente.nl, but I have no idea what might be causing it. The RADIUS service will be shut down permanently from 1 april onwards, so we need to figure out what this is and transfer it.

**Comment by jeffreybakker** [comment]
@Kurocon It has been >2 years, I think we can close this issue?
