### ISSUE TITLE
SaltStack vulnerability

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#36]
SaltStack on our servers is outdated, and vulnerabilities have been found in versions 3002 and below. We currently run 3001 and below, as low as 2018.3.4 even, so these needs to be updated soon.

https://www.saltstack.com/blog/active-saltstack-cve-announced-10-30-20/

**Comment by jeffreybakker** [comment]
All servers were already version >3003, except for the following containers, which have been manually updated:

- ia-pandora
- ia-files
- ia-backup
- bb-dns
- ia-commissies
- stoetenwolf
