### ISSUE TITLE
Wiki update FlitCie + Cinema => MediaCie

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/Beheer_Issues#38]
Now we created the MediaCie and deleted the FlitCie and Cinema, the people in the MediaCie don't have access to the wiki pages of the two committees anymore.

**Comment by Kurocon** [comment]
This is expected behaviour, what do you want us to do exactly? Give the new committee access to the existing pages only, or also create a new wiki prefix for the MediaCie so you can migrate the pages over?

**Comment by bramvandartel** [comment]
Indeed, expected behaviour. I would like to have a new wiki prefix for the MediaCie.

**Comment by bramvandartel** [comment]
Guess what, it seems that I can do things myself! I feel so capable :)
