### ISSUE TITLE
Touchscreen Cookie Corner calibration

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#48]
The touch screen of the cookie corner should be re-calibrated.

See config file to be edited: https://gitlab.ia.utwente.nl/Beheer/salt-config/-/blob/master/salt/kiosk/files/99_touchscreen_calibration.conf

Calibration can maybe be done using https://www.freedesktop.org/wiki/Software/xinput_calibrator/
(just googled for it, not tested or used before)

**Comment by Kurocon** [comment]
Touch screen is broken. We've calibrated it to kind-of match again, but we need to get a new one. I would recommend getting the same ones that are currently in the drink rooms, because they work well and it keeps our hardware consistent.

**Comment by Kurocon** [comment]
This is the drink room touch screen:
https://tweakers.net/pricewatch/1184017/iiyama-prolite-t1731sr-b5-zwart.html

**Comment by jeffreybakker** [comment]
Board has been notified and a replacement will be ordered online

**Comment by Kurocon** [comment]
Done!
