### ISSUE TITLE
fix letsencrypt autorenew on ia-commissies

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#49]

**Comment by jeffreybakker** [comment]
The renew script appears to be faulty

**Comment by jeffreybakker** [comment]
It appears to happen when certificates are requested (or renewed) through means other than calling `certbot renew`. Faulty renewal configurations should be detected and fixed manually (or removed and recreated by salt)

**Comment by TomG777** [comment]
Fixed
