### ISSUE TITLE
migrate from legacy network interface names

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#5]
[Changelog 5.1.5 Migrating from legacy network interface names](https://www.debian.org/releases/buster/amd64/release-notes/ch-information.en.html#migrate-interface-names)

The "old" naming schemes of network interfaces (ie. `eth0` or `wlan0`) will not be officially supported by `udev` in Buster. Similar network interfaces should be renamed to `enp0s1` or `wlp0s1` respectively.

**Comment by Kurocon** [comment]
> it is recommended that you migrate in advance to the new naming scheme
