### ISSUE TITLE
Gitlab runner broken

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#52]
![image](https://user-images.githubusercontent.com/1193988/190069857-e3e883fa-d2ed-4b81-a09e-b71508020e28.png)

Probably related to the firewall changes we did to Glomgold on monday @jeffreybakker 

Would be nice if it is fixed before monday 19 september because the WWW uses it.

**Comment by jeffreybakker** [comment]
Of course, I forgot that this could be a side effect. I'll look into it

**Comment by jeffreybakker** [comment]
GitLab runner is back online, the k8s dashboard is still open, the K8S api (port `6443`) has been blocked, however, SSH to `ia-k8s` does not appear to respond, this will be researched later this week

**Comment by jeffreybakker** [comment]
The issues regarding the firewall have been fixed
