### ISSUE TITLE
merge binary directories to /usr

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#6]
[Changelog 2.2.12 Merged /usr on fresh installs](https://www.debian.org/releases/buster/amd64/release-notes/ch-whats-new.en.html#merged-usr)

From Debian Buster the binary directories `/bin`, `/sbin` and `/lib` will be merged into the `/usr` directory. This will not break anything when upgrading, but might be something to look for when installing third-party software.

This can easily be fixed with the provided `usrmerge` package.

**Comment by Kurocon** [comment]
> When upgrading to buster, systems are left as they are
