### ISSUE TITLE
install gaming shuttle in the "chill area" of the association room

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#64]

**Comment by kasteelharry** [comment]
PC has been set up. Only thing that is missing is the bluetooth keyboard and as soon that has been delevired we can close this issue and the PC can be put in place.

**Comment by kasteelharry** [comment]
Games have to be installed by beheer.

**Comment by jeffreybakker** [comment]
Keyboard will be ordered soon

**Comment by kasteelharry** [comment]
Keyboard has arrived and pc has been setup
