### ISSUE TITLE
Central auth platform

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#67]
Setup a central authentication platform with LDAP/AD as backend, with support for clients using (at least) oAuth and SAML, with support for adding two-factor authentication. For future use in IA services and the IA website

**Comment by jeffreybakker** [comment]
I came across this one recently:
https://goauthentik.io/

Maybe this is something for IA?

**Comment by Kurocon** [comment]
Looks good, let's try it out (I see it also has a helm chart :D )

**Comment by Kurocon** [comment]
Authentik is a no-go, it does not support nested AD groups, and from the issues it doesn't seem they are working on it.

[KeyCloak](https://www.keycloak.org/) is an alternative that I'm going to try, with the [bitnami helm chart](https://artifacthub.io/packages/helm/bitnami/keycloak)

**Comment by Kurocon** [comment]
Done!
