### ISSUE TITLE
archive symposiumzephyrus.nl

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/Beheer_Issues#71]
The board has requested us to archive the website and cancel the domain name

**Comment by jeffreybakker** [comment]
An initial attempt has been made to save the site to inter-archief.net.

Furthermore, the domain will be cancelled per September 2023. WWW has been asked to remove all personal aliases. Finally, the domain can be removed from Google Workspaces

**Comment by Kurocon** [comment]
Done!
