### ISSUE TITLE
Monitoring: logged in users check fails even with user logged in

### ISSUE THREAD

**Issue by kasteelharry** [Inter-Actief/Beheer_Issues#79]
As stated in the title. When the computer is off, it has the following error:
```
CHECK_NRPE STATE CRITICAL: Socket timeout after 10 seconds.
```

When a user is logged in, it fails with:
```
CHECK_NRPE: (ssl_err != 5) Error - Could not complete SSL handshake with [IP_ADDRESS]: 1
```

The check should succeed in checking if there is someone logged in when on. When the computer is off, it should not check or give an different result.

Suspected issue:
Something wrong in the Windows domain. I cannot investigate any further

**Comment by Kurocon** [comment]
Monitoring is pretty much dead, so I doubt we still need this
