### ISSUE TITLE
Deploy Ghost in kubernetes for IO/Vivat

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#84]
The IO Vivat committee wants to use Ghost for online publications. We need to deploy this in our Kubernetes cluster.
https://ghost.org/docs/install/

For now under a subdomain but later on a custom domain when all data has been configured.

Helm chart: https://artifacthub.io/packages/helm/bitnami/ghost

**Comment by Kurocon** [comment]
Deployed on vivat.k8s.ia.utwente.nl
Will be configured by Vivat chief editor
Domain will be transfered when done, and we can switch it over.

**Comment by kasteelharry** [comment]
Domain has been transferred and pipeline for updating the deployment has been built. Closing this issue for now.
