### ISSUE TITLE
Netdata on glomgold inaccesible

### ISSUE THREAD

**Issue by TomG777** [Inter-Actief/Beheer_Issues#85]
The IA-www3 container does not have access to netdata (port 19999) on glomgold. This causes the /glomgold endpoint for netdata to timeout/drop.
Even though the firewall rules on glomgold would suggest that this port is accepted from www3, packets do not seem to arrive past the firewall.

We have checked with tcpdump and they go through magicka so it does not seem to be a host issue from lxc.
Netdata is also correctly running on glomgold (tested by using ssh forwarding on port 19999).

**Comment by jeffreybakker** [comment]
It works again
