### ISSUE TITLE
Weblate for WWW

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/Beheer_Issues#93]
The WWW would like to use Weblate for easier translations. Weblate is paid, but they offer a free selfhosted version which would be nice! We want to use the git intergration for automatic pull requests as well, which should be supported.

https://docs.weblate.org/en/latest/admin/install/kubernetes.html

**Comment by jeffreybakker** [comment]
Looks good. Is this just for amelie, or will can/will this software also be used for other projects?

**Comment by Kurocon** [comment]
I don't mind using it for other projects as well in the future, but to start it will only be Amelie

**Comment by Kurocon** [comment]
Installed and it is in use, and seems to be working fine!
